name: laraflutter
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  print_color: ^3.0.5
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  flutter_screenutil: ^5.9.0
  get_storage: ^2.1.1
  country_picker: ^2.0.23

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    # images
    - assets/images/logo.png

  uses-material-design: true
